export const TypesData = [
    {
        id: 'artist',
        title: 'The Artist',
        tagline: 'Seeing beauty, creating beauty.',
        bgColor: '#df3e51',
        creativeStrength: 'Ability to bring ideas and concepts to life',
        untappedPotential: 'Becoming totally fearless in your expression',
        collabrator: 'The Producer',
        tweetText: "My creative type is Artist, and we're known for bringing ideas to life.",
        definition: ['As an ARTIST, you need to create in order to feel truly alive. Full of ideas and visions, you’re driven by the desire to express yourself and transform the world around you.',
            'The ARTIST type lives in the space between the inner and outer worlds, and your gift is the ability to powerfully manifest what’s inside of you. That’s not always an easy task, but with it comes the capacity to create works that speak to others on a deep level and inspire new ways of seeing the world.',
            'With your love of beauty and your connection to the senses, you have a strong aesthetic orientation and you crave well-designed environments. Whatever creative field you end up pursuing, you tend to work best on your own and crave the independence that lets you freely follow your creative impulses. You’re at home in a state of flow—easily becoming so engrossed in whatever project you’re working on that you lose all sense of time and space.',
            'Your biggest challenge is working through creative blocks stemming from your emotional nature. You know well that in the “war of art,” fear and self-doubt are your biggest enemies. Practice diplomacy instead of waging war, and you’ll learn to turn enemies into trusted allies pointing you in the direction of creative greatness; in other words, listening to your fear can tell you exactlywhat you need to do.',
            'Together, the ARTIST and the PRODUCER form a powerful creative duo with the vision and drive to manifest ideas on a large scale. Seek out collaborations with the dynamic and pragmatic PRODUCER to amplify your impact and take your projects across the finish line.']
    },
    {
        id: 'thinker',
        title: 'The Thinker',
        tagline: 'Deep thoughts,big questions.',
        bgColor: '#a19989',
        creativeStrength: 'Intellectual curiosity, ability to find and create meaning',
        untappedPotential: 'Bridging theory and practice, applying ideas in real life',
        collabrator: 'The Adventurer',
        tweetText: "My creative type is Thinker, and we're known for our intellectual curiosity.",
        definition: ['For the Thinker, the examined life is truly the only one worth living. Ever the perpetual student, you experience the world as an endless opportunity for learning, discovery, and truth-seeking.',
            'Driven by an insatiable intellectual curiosity, the THINKER makes the quest for knowledge and truth a lifelong pursuit. With all those big questions and abstract thinking, you’ve got some serious electrical activity going on in that brain of yours! Few things satisfy your inquisitive mind more than a well-formulated question or an elegant solution, and you’re content to spend much of your time alone, studying topics that fascinate you and engaging with your inner world of ideas.',
            'Your greatest gifts are your sense of wonder and depth of perception. You can see the big picture and the deeper meaning of almost any situation in a way that few others can. Your biggest challenges? Getting out of your head and learning to balance theory with practice. Try not to get too caught up in concepts and abstractions, dear THINKER. Great ideas are meant to be brought to life.',
            'Seek out the company of ADVENTURER types, who provide the perfect counterbalance to your introspective and analytical nature. The infectious energy and playful spirit of the ADVENTURER remind you to embrace the joys of creation—and to not be afraid to get your hands a little dirty in the process.']
    },
    {
        id: 'adventurer',
        title: 'The Adventurer',
        tagline: 'So much inspiration, so little time',
        bgColor: '#da552d',
        creativeStrength: 'High levels of creative energy, spirit of curiosity and play',
        untappedPotential: 'Committing yourself to developing one particular skill or project',
        collabrator: 'The Artist',
        tweetText: "My creative type is Adventurer, and we're natural storytellers.",
        definition: ['There’s no telling where the impassioned creative quest and endless curiosity of the ADVENTURER may lead. Fueled by high energy levels and boundless enthusiasm, you’re easily inspired—and more than willing to follow your fascinations wherever they take you.',
            'ADVENTURER types are passionate, expressive, multi-talented creative spirits with a natural ability to entertain and inspire. As an ADVENTURER, you’re never satisfied to just come up with ideas. Instead, you have an almost compulsive need to act on them. Your abundant energy fuels you in the pursuit of many interests, hobbies, areas of study, and artistic endeavors. You’re a fast learner, able to pick up new skills and juggle different projects and roles with relative ease. A true Renaissance person, you’re likely to develop expertise in a number of areas over the course of your life and career.',
            'You have a huge amount of energy that needs to be released on a regular basis. When your energy doesn’t have anywhere meaningful to go, you can easily become frustrated, aimless, and even depressed. Keep it moving! It’s critical to find fulfilling creative outlets—including ones that you commit to developing over time.',
            'A people-person with deep emotions and empathy, ADVENTURERs are natural storytellers and performers. You have a powerful ability to inspire and are at your best when you’re sharing your creative expressions with others. ADVENTURERs have mastered one of the most elusive and powerful secrets of creativity: the more freely you give of your talents for the benefit of others, the more you earn the divine favor of the Muses. Keep the inspiration in circulation, and it will come back to you tenfold.',
            'Seek out collaborations with ARTIST types to jointly explore new creative horizons. The ARTIST’s connection to the deeper sources of inspiration will inspire you to direct your adventurous spirit toward journeys of self-exploration.']
    },
    {
        id: 'maker',
        title: 'The Maker',
        tagline: 'Comitted to your craft',
        bgColor: '#4b9d81',
        creativeStrength: 'Focus and dedication, ability to achieve mastery',
        untappedPotential: 'Taking creative risks, finding joy and play in the process',
        collabrator: 'The Visionary',
        tweetText: "My creative type is Maker, and we're known for our focus and dedication.",
        definition: ['Driven, focused, and dedicated to the creative process, the MAKER has mastered the art of manifesting ideas and visions in three-dimensional form. Society greatly benefits from the work of MAKER types, who develop the systems, structures, tools, and innovations that the rest of us rely on.',
            'One of the hardest workers of all the types, the MAKER is almost always busy solving problems, making headway on personally meaningful goals, and completing projects. There are few things that bring you more satisfaction than applying your brain power to crafting things and making progress in any form. You tend to excel in design, crafts, architecture, and other fields that blend artistry with business and technology.',
            'You’re driven by tangible results, and you know how to deliver. A quiet type, you enjoy collaboration but generally prefer to work alone so you can focus on your own creative process.',
            'You know how to play the long game, and you’re not afraid to do the unglamorous legwork that goes into building something of value over time. Your gifts of focus and dedication can lead to achieving mastery and coming to be seen by others as an authority in your field.',
            'Your biggest challenge? To connect more deeply with your intuition and emotions in order to bring forth ever more authentic and original work. Productivity is only half the equation of doing great work—the other half is inspiration. Creating the space to dream, imagine, and play can keep your work from becoming rote and mechanical.',
            'Combine forces with the enterprising VISIONARY to take your creativity to new heights. The VISIONARY’s soaring imagination gives you permission to dream bigger and envision the impossible—and to fearlessly risk failure in order to make it a reality.']
    },
    {
        id: 'producer',
        title: 'The Producer',
        tagline: 'Process is power',
        bgColor: '#3ca0a0',
        creativeStrength: 'Strong leadership skills, ability to make things happen',
        untappedPotential: 'Balancing productivity with purpose',
        collabrator: 'The Dreamer',
        tweetText: "My creative type is Producer, and we're known to be results-driven.",
        definition: ['The PRODUCER is the quintessential “doer” of all the creative types. People-oriented, analytical, pragmatic, and dynamic, you have a highly creative nature that’s balanced by a grounded realism and “get it done” attitude. In your eyes, an idea has real value only when it’s turned into something that others can enjoy and benefit from.',
            'Highly goal-oriented and results-driven, you pursue your desired outcomes with a laser-like focus. You derive great pride and satisfaction from your ability to implement ideas, and you find joy in the process of creation with all its ups and downs. A natural organizer with an ability to motivate and inspire others, you gravitate to collaborative and leadership roles. You know how to make everything, and everyone, work together to see a project through to the end.',
            'Along with your intellectual prowess and strong work ethic, your greatest strength is your ability to keep a cool head and single-pointed focus as you work through any and all challenges that arise during the creative process. But while you’re keeping your eyes on the prize, don’t get too fixated on results. Your greatest challenge is anchoring your productivity in a deeper sense of purpose. You’ll tap into your true creative depths when you can tune into the voice of your intuition and use it as a source of guidance.',
            'Seek out the company of idealistic and imaginative DREAMER types, who remind you that there is limitless inspiration to be found within. Let the DREAMER spark your imagination and inspire you to think even bigger.']    
    },
    {
        id: 'dreamer',
        title: 'The Dreamer',
        tagline: 'The power of imagination unleashed',
        bgColor: '#892078',
        creativeStrength: 'Connection to emotions and imagination, empathy and sensitivity',
        untappedPotential: 'Using dreams to fuel real-world action',
        collabrator: 'The Innovator',
        tweetText: "My creative type is Dreamer, and we're known for our empathy and imagination.",
        definition: ['The world is a place of beauty and magic in the eyes of a DREAMER. Where others see facts and figures, you see symbols, metaphors, and hidden meanings.',
            'You’re deeply emotional and intuitive, with a vivid imagination—the quintessential idealist and romantic. The inner world is always where you’ve felt most at home. You’re happy to roam your mental landscape of thoughts, emotions, and fantasies for hours on end.',
            'You’re naturally drawn to express your inner world through literary pursuits, music, and the visual arts. Think of yourself as the “magical realist” of the creative types: like the literary masters of that genre, you naturally infuse your everyday life with the beauty and wonder of the imagination.',
            'Your greatest gift is your depth of sensitivity and empathy, which allows you to give voice to universal human emotions in a way that touches people on a profound level. Your greatest challenge is learning to balance dreaming with disciplined action—which starts with coming back to the present moment. Let your mind roam free, DREAMER, but don’t forget to return to the here and now. Practicing mindfulness will go a long way in helping you turn your dreams into reality.',
            'Seek out opportunities to collaborate with INNOVATOR types, who combine your lofty idealism with a focus on pragmatic solutions. The grounding energy of the INNOVATOR can inspire you to apply your imagination to real-world change.']
    },
    {
        id: 'innovator',
        title: 'The Innovator',
        tagline: 'Move, shake, disrupt, repeat',
        bgColor: '#2e5096',
        creativeStrength: 'Ability to generate new ideas and innovative solutions',
        untappedPotential: 'Mastering the art of executing ideas',
        collabrator: 'The Maker',
        tweetText: "My creative type is Innovator, and we're known for our inventive ideas.",
        definition: ['The INNOVATOR sees everything through the lens of possibilities and progress, problems and solutions. You feel the most yourself when you’re using your intellectual and creative powers to solve problems and dream up new and improved ways of doing things. Your attention is largely focused on the world around you, and you’re constantly probing its structures and systems to find ways to push things forward.',
            'Change may be scary for most people, but for you, it’s fuel for your creative fire. A pioneer and trailblazer, you’re here on this planet to light the way into the future, helping the rest of us learn to adapt and thrive in times of rapid and unpredictable change.',
            'You’re a natural risk-taker, with an insatiable desire to expand boundaries and explore uncharted territories. You’re not one to do things the way they’ve always been done. You thrive when working in service of large-scale change and progress, and your talents equip you well for roles that allow you to experiment and play with ideas.',
            'Beware when the initial spark of inspiration starts to wear off and you feel tempted to move on to the next big thing a little too quickly. INNOVATORS tap into their greater potential when they learn to master the art of the follow-through. By finding joy in the “messy middle” of a venture—not just the excitement of the beginning or the satisfaction of reaching the finish line—you’ll become a true creative powerhouse.',
            'Seek out creative partnerships with MAKER types, who have the stamina and dedication to take any idea from concept to completion. Seeing the MAKER in action reminds you that taking it one step at a time is a much more effective creative strategy than racing to the finish line.']
    },
    {
        id: 'visionary',
        title: 'The Visionary',
        tagline: 'Imagining the impossible',
        bgColor: '#fca63f',
        creativeStrength: 'Full of big ideas, ability to see potential and possibility everywhere',
        untappedPotential: 'Using your visions to fuel consistent daily action',
        collabrator: 'The Thinker',
        tweetText: "My creative type is Visionary. We're known to be charismatic and expressive.",
        definition: ['You live in a world of infinite possibilities, preferring to see things not as they are but as they could be. You know that life is limited only by the boundaries of your own beliefs, and you’re driven to push the limits of, well, everything.',
            'Emotional, passion-driven, and full of ideas, the VISIONARY combines a vivid imagination with a desire for practical solutions. Your introspective and intuitive nature is balanced by a keen interest in the world around you and a desire to contribute to society.',
            'Charismatic and expressive, you love sharing your ideas and visions with others and creating community around shared values and ideals. Your greatest gift? The ability to see the spark of potential in everything and everyone, and to inspire others to see it, too. You’re able to guide people toward an invisible horizon with a rare generosity of spirit and strength of conviction.',
            'Don’t get stuck in the dreaming stage, VISIONARY. Your greatest challenge—and true power—lies in learning to take consistent daily action to create the future you envision.',
            'Seek out the “voice of reason” of the THINKER type to help you take a grounded, rational approach to your creative work. The THINKER’s deep perception and probing intellect lend a powerful clarity that can bring your visions into sharper focus.']
    }
]